// Human-readable HTML sitemap served at /sitemap. Crawler-friendly index
// of every public page on the site — static routes plus every event,
// restaurant, and news article. Sits alongside the machine-readable
// /sitemap.xml (generated by app/sitemap.ts); both stay in sync because
// they fetch the same lists from the same endpoints.

import type { Metadata } from "next";
import NextLink from "next/link";
import { Box, Typography, Divider } from "@mui/material";
import Grid from "@mui/material/Grid2";
import { serverGet } from "@/lib/serverFetch";
import { eventUrl, restaurantUrl } from "@/lib/eventUrl";
import {
  ARTICLES,
  ARTICLE_CATEGORIES,
  articleUrl,
  getArticlesByCategory,
} from "@/lib/articles";
import type { BayanihanEvent, NewsArticle, Restaurant } from "@/types";

export const metadata: Metadata = {
  title: "Site map — All pages on Bayanihan.com",
  description:
    "Complete list of every page on Bayanihan.com: events, restaurants, news, and static pages.",
  alternates: { canonical: "/sitemap" },
  openGraph: {
    title: "Site map — All pages on Bayanihan.com",
    description:
      "Complete list of every page on Bayanihan.com: events, restaurants, news, and static pages.",
    url: "/sitemap",
    type: "website",
  },
};

// Static, hand-maintained list. Order matters — these render in the
// "Pages" column in the same order the user sees them in the nav.
const STATIC_PAGES: Array<{ path: string; label: string }> = [
  { path: "/", label: "Home" },
  { path: "/browse-events", label: "Browse Events" },
  { path: "/restaurant", label: "Restaurants" },
  { path: "/news", label: "News" },
  { path: "/global-calendar", label: "Global Calendar" },
  { path: "/about", label: "About" },
  { path: "/articles", label: "Articles & Insights" },
  { path: "/contact-us", label: "Contact Us" },
  { path: "/sign-in", label: "Sign In" },
  { path: "/registration", label: "Register" },
];

interface EventsResponse {
  data?: { events?: BayanihanEvent[] };
  events?: BayanihanEvent[];
}

interface RestaurantsResponse {
  data?: { restaurant?: Restaurant[]; restaurants?: Restaurant[] };
  restaurant?: Restaurant[];
}

interface NewsResponse {
  data?: NewsArticle[];
  meta?: { last_page?: number };
}

async function fetchEvents(): Promise<BayanihanEvent[]> {
  try {
    const root = await serverGet<EventsResponse | BayanihanEvent[]>("events", {
      revalidate: 600,
    });
    if (Array.isArray(root)) return root;
    if (Array.isArray(root?.data?.events)) return root.data!.events!;
    if (Array.isArray(root?.events)) return root.events!;
    return [];
  } catch {
    return [];
  }
}

async function fetchRestaurants(): Promise<Restaurant[]> {
  try {
    const root = await serverGet<RestaurantsResponse>("restaurants", {
      revalidate: 600,
    });
    const arr =
      root?.data?.restaurants ??
      root?.data?.restaurant ??
      root?.restaurant ??
      [];
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

// Fetch every news page in parallel so the sitemap reflects the entire
// archive rather than just the first page. Mirrors the loop pattern used
// by NewsContent on the /news page.
async function fetchAllNews(): Promise<NewsArticle[]> {
  try {
    const first = await serverGet<NewsResponse>("news-articles-v2?page=1", {
      revalidate: 600,
    });
    const firstItems = Array.isArray(first?.data) ? first.data : [];
    const lastPage =
      typeof first?.meta?.last_page === "number" ? first.meta.last_page : 1;
    if (lastPage <= 1) return firstItems;
    const more = await Promise.all(
      Array.from({ length: lastPage - 1 }, (_, i) =>
        serverGet<NewsResponse>(`news-articles-v2?page=${i + 2}`, {
          revalidate: 600,
        })
          .then((r) => (Array.isArray(r?.data) ? r.data : []))
          .catch(() => [] as NewsArticle[])
      )
    );
    return [...firstItems, ...more.flat()];
  } catch {
    return [];
  }
}

function formatDate(input?: string | null): string | null {
  if (!input) return null;
  const d = new Date(input);
  if (isNaN(d.getTime())) return null;
  return d.toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function SectionHeader({
  title,
  count,
}: {
  title: string;
  count: number;
}) {
  return (
    <Box sx={{ mb: 2, display: "flex", alignItems: "baseline", gap: 1 }}>
      <Typography
        component="h2"
        sx={{
          fontWeight: 800,
          fontSize: { xs: 18, md: 20 },
          color: "#0f172a",
          fontFamily: "var(--font-urbanist), 'Outfit', sans-serif",
        }}
      >
        {title}
      </Typography>
      <Typography
        sx={{
          fontSize: 13,
          fontWeight: 700,
          color: "#94a3b8",
          fontFamily: "var(--font-outfit), 'Outfit', sans-serif",
        }}
      >
        ({count.toLocaleString()})
      </Typography>
    </Box>
  );
}

function SitemapLink({
  href,
  primary,
  secondary,
}: {
  href: string;
  primary: string;
  secondary?: string | null;
}) {
  return (
    <Box
      component={NextLink}
      href={href}
      sx={{
        display: "block",
        py: 0.75,
        px: 1,
        mx: -1,
        borderRadius: 1,
        textDecoration: "none",
        color: "inherit",
        transition: "background-color .15s",
        "&:hover": {
          backgroundColor: "#fff4dd",
          "& .sm-primary": { color: "#c2410c" },
        },
      }}
    >
      <Typography
        className="sm-primary"
        sx={{
          fontSize: 14,
          fontWeight: 600,
          color: "#1e293b",
          lineHeight: 1.35,
          transition: "color .15s",
          // Truncate long titles to one line.
          display: "-webkit-box",
          WebkitLineClamp: 1,
          WebkitBoxOrient: "vertical",
          overflow: "hidden",
        }}
      >
        {primary}
      </Typography>
      {secondary && (
        <Typography
          sx={{
            fontSize: 11.5,
            color: "#64748b",
            mt: 0.1,
            fontFamily: "var(--font-outfit), 'Outfit', sans-serif",
          }}
        >
          {secondary}
        </Typography>
      )}
    </Box>
  );
}

export default async function SitemapPage() {
  const [events, restaurants, news] = await Promise.all([
    fetchEvents(),
    fetchRestaurants(),
    fetchAllNews(),
  ]);

  // Drop items without a usable URL so we never emit dead links.
  const eventEntries = events
    .map((e) => ({ url: eventUrl(e), title: e.title, date: e.eventDate || e.date }))
    .filter((e) => e.url);
  const restaurantEntries = restaurants
    .map((r) => ({
      url: restaurantUrl(r),
      title: r.name,
      location: [r.city, r.country].filter(Boolean).join(", "),
    }))
    .filter((r) => r.url);
  const newsEntries = news
    .filter((a) => a.slug)
    .map((a) => ({
      url: `/news/${a.slug}`,
      title: a.title || "Untitled article",
      date: a.published_at || a.date || a.created_at,
    }));

  return (
    <Box
      component="main"
      sx={{
        bgcolor: "#fff",
        minHeight: "100vh",
        py: { xs: 5, md: 7 },
      }}
    >
      <Box
        sx={{
          width: "100%",
          maxWidth: 1280,
          mx: "auto",
          px: { xs: 2, sm: 3, md: 4 },
        }}
      >
        {/* Header */}
        <Box sx={{ mb: { xs: 3, md: 4 } }}>
          <Typography
            component="h1"
            sx={{
              fontWeight: 900,
              fontSize: { xs: 28, md: 36 },
              lineHeight: 1.1,
              letterSpacing: "-0.02em",
              color: "#0f172a",
              fontFamily: "var(--font-urbanist), 'Outfit', sans-serif",
              mb: 1,
            }}
          >
            Site map
          </Typography>
          <Typography
            sx={{
              fontSize: { xs: 14, md: 15 },
              color: "#475569",
              maxWidth: 700,
              lineHeight: 1.55,
              fontFamily: "var(--font-outfit), 'Outfit', sans-serif",
            }}
          >
            Every public page on Bayanihan.com in one place — static pages,
            events, restaurants, and news articles. Looking for the
            machine-readable version?{" "}
            <Box
              component="a"
              href="/sitemap.xml"
              sx={{
                color: "#c2410c",
                textDecoration: "underline",
                fontWeight: 700,
              }}
            >
              View sitemap.xml
            </Box>
            .
          </Typography>
        </Box>

        <Divider sx={{ mb: { xs: 3, md: 4 } }} />

        {/* Sections */}
        <Grid container spacing={{ xs: 4, md: 5 }}>
          {/* Pages */}
          <Grid size={{ xs: 12, md: 4 }}>
            <SectionHeader title="Pages" count={STATIC_PAGES.length} />
            <Box>
              {STATIC_PAGES.map((p) => (
                <SitemapLink
                  key={p.path}
                  href={p.path}
                  primary={p.label}
                  secondary={p.path}
                />
              ))}
            </Box>
          </Grid>

          {/* Events */}
          <Grid size={{ xs: 12, md: 4 }}>
            <SectionHeader title="Events" count={eventEntries.length} />
            {eventEntries.length === 0 ? (
              <Typography sx={{ fontSize: 13, color: "#94a3b8" }}>
                No events available.
              </Typography>
            ) : (
              <Box>
                {eventEntries.map((e, i) => (
                  <SitemapLink
                    key={e.url + i}
                    href={e.url}
                    primary={e.title || "Untitled event"}
                    secondary={formatDate(e.date)}
                  />
                ))}
              </Box>
            )}
          </Grid>

          {/* Restaurants */}
          <Grid size={{ xs: 12, md: 4 }}>
            <SectionHeader
              title="Restaurants"
              count={restaurantEntries.length}
            />
            {restaurantEntries.length === 0 ? (
              <Typography sx={{ fontSize: 13, color: "#94a3b8" }}>
                No restaurants available.
              </Typography>
            ) : (
              <Box>
                {restaurantEntries.map((r, i) => (
                  <SitemapLink
                    key={r.url + i}
                    href={r.url}
                    primary={r.title || "Restaurant"}
                    secondary={r.location || null}
                  />
                ))}
              </Box>
            )}
          </Grid>

          {/* News — full-width row below so long article titles get room */}
          <Grid size={{ xs: 12 }}>
            <Divider sx={{ mb: { xs: 3, md: 4 } }} />
            <SectionHeader title="News articles" count={newsEntries.length} />
            {newsEntries.length === 0 ? (
              <Typography sx={{ fontSize: 13, color: "#94a3b8" }}>
                No news articles available.
              </Typography>
            ) : (
              <Grid container spacing={{ xs: 0, md: 2 }}>
                {newsEntries.map((n, i) => (
                  <Grid size={{ xs: 12, sm: 6, md: 4 }} key={n.url + i}>
                    <SitemapLink
                      href={n.url}
                      primary={n.title}
                      secondary={formatDate(n.date)}
                    />
                  </Grid>
                ))}
              </Grid>
            )}
          </Grid>

          {/* Articles & Insights — static editorial pages, grouped by
              category to mirror the footer's "Explore More" columns. */}
          <Grid size={{ xs: 12 }}>
            <Divider sx={{ mb: { xs: 3, md: 4 } }} />
            <SectionHeader title="Articles & Insights" count={ARTICLES.length} />
            <Grid container spacing={{ xs: 3, md: 4 }}>
              {ARTICLE_CATEGORIES.map((cat) => (
                <Grid size={{ xs: 12, sm: 6, md: 4 }} key={cat.key}>
                  <Typography
                    sx={{
                      fontWeight: 800,
                      fontSize: 14.5,
                      color: "#334155",
                      mb: 1,
                      fontFamily: "var(--font-urbanist), 'Outfit', sans-serif",
                    }}
                  >
                    {cat.title}
                  </Typography>
                  {getArticlesByCategory(cat.key).map((a) => (
                    <SitemapLink
                      key={a.slug}
                      href={articleUrl(a.slug)}
                      primary={a.title}
                    />
                  ))}
                </Grid>
              ))}
            </Grid>
          </Grid>
        </Grid>
      </Box>
    </Box>
  );
}
